language: python
# python managed by conda until 3.7 available
# python:
# - '3.6'
addons:
  apt:
    packages:
    - verilator    
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

install:
# install conda for py 3.7
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7
- source activate test-env
- conda install pip
# End install conda
- source .travis/coreir_install.sh
- pip install twine
- pip install python-coveralls
- pip install pytest-cov pytest-codestyle fault
- pip install --ignore-installed -r requirements.txt
- pip install -e .
after_success:
- coveralls
jobs:
  include:
  - stage: test
    script:
    - py.test --cov magma -v --cov-report term-missing tests
  - stage: trigger downstream
    script: |
      # See https://github.com/mernst/plume-lib/blob/master/bin/trigger-travis.sh for documentation
      echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
      if [[ ($TRAVIS_BRANCH == master) &&
            ($TRAVIS_PULL_REQUEST == false) ]] ; then
        curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
        sh trigger-travis.sh --pro David-Durst aetherling $TRAVIS_ACCESS_TOKEN
        sh trigger-travis.sh --pro StanfordAHA garnet $TRAVIS_ACCESS_TOKEN
        sh trigger-travis.sh phanrahan mantle $TRAVIS_ORG_ACCESS_TOKEN
      fi
  - stage: docs
    script: curl -X POST -d "token=$READ_THE_DOCS_TOKEN" https://readthedocs.org/api/v2/webhook/magma/55300/
  - stage: deploy
    if: tag IS present
    script: skip
    deploy: 
      provider: script
      script: /bin/bash .travis/deploy.sh
      skip_cleanup: true
      on:
        tags: true
        branch: master
